---
- name:  "Ansible 2.5+ required"
  assert:
    that:
      - ansible_version is defined
      - ansible_version.full is version_compare('2.13', '>=')
    msg: "Required Ansible version is 2.13+"
    quiet: true
- name: "Debian version check"
  assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version is version('10','>=')
    msg: "Required version is 10+, this is {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
    quiet: true

# IGTF certification authorities
- name: "install gpg"
  apt:
    name: gpg

- name: "create /etc/apt/keyrings"
  file:
    state: directory
    path: /etc/apt/keyrings
    owner: root
    group: root
    mode: '0755'

- name: "add EGI IGTF repository key"
  get_url:
    url: "https://dl.igtf.net/distribution/current/GPG-KEY-EUGridPMA-RPM-4"
    dest: /etc/apt/keyrings/igtf.asc
    force: false

- name: "clean old line without signed-by"
  lineinfile:
    path: /etc/apt/sources.list.d/igtf.list
    line: "deb http://repository.egi.eu/sw/production/cas/1/current egi-igtf core"
    state: absent

- name: "add EGI IGTF repository"
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/igtf.asc] http://repository.egi.eu/sw/production/cas/1/current egi-igtf core"
    filename: "igtf"
    state: present
    update_cache: true

- name: "install latest IGTF certificates"
  apt:
    name: ca-policy-egi-core
    state: present
    update_cache: yes
  register: egi_core_policy

- name: "install fetch-crl"
  apt:
    name: fetch-crl
    update_cache: yes
  notify: "fetch CRLs"

- name: "disable error emails from fetch-crl"
  lineinfile:
    dest: /etc/fetch-crl.conf
    insertafter: EOF
    line: "noerrors"

- name: "script for restarting Apache after fetching new CRLs"
  when: configure_apache_restart_after_fetch
  copy:
    dest: /etc/grid-security/fetch-crl-restart-apache.sh
    mode: 0755
    src: "{{ fetch_crl_restart_script }}"

- name: "configure fetch-crl to call script for restarting Apache after fetching new CRLs"
  when: configure_apache_restart_after_fetch
  copy:
    dest: /etc/fetch-crl.d/restart-apache.conf
    content: |
      postexec=/etc/grid-security/fetch-crl-restart-apache.sh

- name: "enable and start fetch-crl-cron service"
  service:
    name: fetch-crl-cron
    enabled: true
    state: started

- name: "install TERENA_SSL_CA_3 and TERENA_SSL_High_Assurance_CA_3 to be accepted as client CAs"
  when: igtf_cas_install_terena_ssl
  loop:
    - TERENA_SSL_CA_3.pem
    - TERENA_SSL_CA_3.info
    - TERENA_SSL_High_Assurance_CA_3.info
    - TERENA_SSL_High_Assurance_CA_3.pem
    - DigiCert_High_Assurance_EV_Root_CA.info
    - DigiCert_High_Assurance_EV_Root_CA.pem
  copy:
    dest: /etc/grid-security/certificates/
    src: "{{ item }}"
  notify: "rehash certs"

- name: "create script for filtering out CAs confusing Apache"
  copy:
    src: files/accepted_cas.sh
    dest: /etc/grid-security/accepted_cas.sh
    owner: root
    group: root
    mode: '0755'

- name: "create filtered list of CAs"
#  when: egi_core_policy.changed
  command:
    cmd: /etc/grid-security/accepted_cas.sh
    chdir: /etc/grid-security/certificates/

- name: "flush handlers"
  meta: flush_handlers
